language: csharp
solution: PointOfSale/PointOfSale.sln
install:
  - nuget restore PointOfSale/PointOfSale.sln
  - nuget install NUnit.Runners -Version 3.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release PointOfSale/PointOfSale.sln
  - mono ./testrunner/NUnit.Console.3.0.0/tools/nunit3-console.exe ./PointOfSale/PointOfSale.Tests/bin/Release/PointOfSale.Tests.dll


